# Generated by Django 4.1.3 on 2022-11-21 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', flags=re.RegexFlag['IGNORECASE'], inverse_match=False, message='input correct phone', regex='^\\+?1?\\d{8,15}$')])),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telephones', to='book_app.nickname')),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='input correct email')]),
        ),
        migrations.DeleteModel(
            name='Happy',
        ),
    ]
