# Generated by Django 4.1.3 on 2022-11-26 20:33

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_nickname_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator(message='input correct email')]),
        ),
        migrations.AlterField(
            model_name='nickname',
            name='nickname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='nickname',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(code='invalid', flags=re.RegexFlag['IGNORECASE'], inverse_match=False, message='input correct phone', regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(code='invalid', flags=re.RegexFlag['IGNORECASE'], inverse_match=False, message='input correct phone', regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
